### ISSUE TITLE
UX issue with iOS

### ISSUE THREAD

**Issue by tyrtok** [quark-dev/Phonon-Framework#110]
Hi, I tested the framework on iphone5s. 

It feels like the button (arrow) / (sync) is too close to the border on iOS. u might have issues with selecting them on a normal basis. 

[http://img.photobucket.com/albums/v625/hihs/photo_2016-03-29_16-20-38_zpsct23utyn.jpg](url)

is there anyway to add a border on top to so that it will push everything down?

**Comment by Qathom** [comment]
Hi,

Thank you for reporting.
Please, can you try to add the following CSS code:
```css
.header-bar .btn, .header-bar .title {
    vertical-align: middle;
}
```

Thanks in advance.
