### ISSUE TITLE
High cpu usage with spinner.

### ISSUE THREAD

**Issue by ecorona** [quark-dev/Phonon-Framework#122]
I was using a spinner in a "loading" page, then change to "main" page when the app is ready (loader page goes to background).

When this happens the cpu usage goes way up.

Resolved removing the spinner.

**Comment by Qathom** [comment]
Hi @ecorona,

Thank you for reporting this and sorry for the late reply.
On which device/OS version are you testing your app?

I do not understand how CSS3 animation can be the cause of high CPU usage..
CSS rule is animation with property `rotate`.

I will search more information about this.

**Comment by John-Henrique** [comment]
@ecorona Can you show us your code?

**Comment by Qathom** [comment]
Hi @ecorona,

I added the property `translateZ(0)` in order to force GPU rendering.
The following code should fix your high CPU:
``` css
@keyframes circleLoading {
  0% {
    -webkit-transform: rotate(0deg) translateZ(0);
            transform: rotate(0deg) translateZ(0);
  }
  100% {
    -webkit-transform: rotate(360deg) translateZ(0);
            transform: rotate(360deg) translateZ(0);
  }
}
```
