### ISSUE TITLE
Can't custom CSS style of checkboxes in theme.css 

### ISSUE THREAD

**Issue by cedced19** [quark-dev/Phonon-Framework#127]
Actually there is no class defined in the theme.css to update color of a checkbox for example. Let me know if I'm wrong.

**Comment by cedced19** [comment]
Here is how I custom the color of a checkbox:
```css
.checkbox :checked + span, .radio :checked + span {
    border-color: #18BC9C;
}
```
The class name comes from Chrome Dev Tool.
